import java.util.List;
import java.util.ArrayList;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    int item1 = 18;
    int item13 = 6;
    int item22 = 8;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
    

        String receipt = "============= Order details =============\n"+
        getMenu(inputs)+
        "-----------------------------------\n"+
        getTotal(inputs)+
        "===================================";
        return receipt;
    }

    public String getMenu(List<String> inputs){
        String receipt = "";
        for (String temp : inputs) {
            String[] parts = temp.split(" ");//split the order ex. ITEM0001 and 1 from ITEM0001 x 1
            String foodNum = parts[0]; // the food code
            int quantity = Integer.parseInt(parts[2]); //quantity of food
            if(foodNum.equals("ITEM0001")){
                receipt += "Braised chicken x "+quantity+" = "+(quantity*item1)+" yuan\n";
            } else if(foodNum.equals("ITEM0013")){
                receipt += "Chinese hamburger x "+quantity+" = "+(quantity*item13)+" yuan\n";
            } else if(foodNum.equals("ITEM0022")){
                receipt += "Cold noodles x "+quantity+" = "+(quantity*item22)+" yuan\n";
            }
        }
        return receipt;
    }

    public String getTotal(List<String> inputs){
        int overallTotal = 0;
        List<String> halfPriceDish = new ArrayList<>();
        List<Integer> halfPriceAmounts = new ArrayList<>();
        for (String temp : inputs) {
            String[] parts = temp.split(" ");//split the order ex. ITEM0001 and 1 from ITEM0001 x 1
            String foodno = parts[0]; // the food code
            int quantity = Integer.parseInt(parts[2]); //quantity of food
            if(foodno.equals("ITEM0001")){
                overallTotal += quantity * item1;
                halfPriceDish.add("Braised chicken");
                halfPriceAmounts.add(18/2);
            } else if(foodno.equals("ITEM0013")){
                overallTotal += quantity * item13;
            } else if(foodno.equals("ITEM0022")){
                overallTotal += quantity * item22;
                halfPriceDish.add("Cold noodles");
                halfPriceAmounts.add(8/2);
            }
        }
        if(halfPriceDish.size() >= 2){
            int savedAmount = halfPriceAmounts.get(0);
            for (int temp : halfPriceAmounts){
                if(!(temp == savedAmount)){
                    savedAmount += temp;
                }
            }

            String halfPromo ="Promotion used:\n" +
            "Half price for certain dishes ("+halfPriceDish.toString().replace("[", "").replace("]", "").replace(", ", "，")+")，saving "+savedAmount+" yuan\n" +
            "-----------------------------------\n";

            return halfPromo+"Total："+(overallTotal-savedAmount)+" yuan\n";

        } else if(overallTotal >= 30){
            String buy30Promo = "Promotion used:\n" +
            "满30减6 yuan，saving 6 yuan\n" +
            "-----------------------------------\n";
            return buy30Promo+"Total："+(overallTotal-6)+" yuan\n";
        }
        else {
            return "Total："+overallTotal+" yuan\n";
        }
    }


}

